[package]
name = "next-web-document-excel"
version = "0.1.0"
edition = "2024"

[dependencies]
fast-excel ={  path = "./fast-excel", version = "*" }
fast-excel-macro ={  path = "./fast-excel-macro", version = "*" }
