[package]
name = "next-web-email"
version = "0.1.0"
edition = "2021"

[dependencies]
lettre = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }

next-web-core   = { workspace = true }
next-web-macros = { workspace = true }
rudi-dev = { workspace = true }